# Generated by Django 5.1.1 on 2024-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.CharField(max_length=10)),
                ('subjectName', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('seatAvailable', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
