# Generated by Django 5.1.1 on 2024-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
            ],
        ),
    ]
