# Generated by Django 5.1.1 on 2024-10-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0004_registersubject_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registersubject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='registersubject',
            name='subjectName',
        ),
        migrations.RemoveField(
            model_name='registersubject',
            name='year',
        ),
    ]
