# Generated by Django 5.1.1 on 2024-10-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0005_remove_registersubject_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersubject',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registersubject',
            name='subjectName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registersubject',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
