# Generated by Django 5.1.1 on 2024-10-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0006_registersubject_semester_registersubject_subjectname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registersubject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='registersubject',
            name='subjectName',
        ),
        migrations.RemoveField(
            model_name='registersubject',
            name='year',
        ),
    ]
